#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

use yii\helpers\ArrayHelper;
use yii\console\Application;

try {
    require __DIR__ . '/vendor/autoload.php';
    require_once __DIR__ . '/config/dotenv.php';

    defined('ADSHOWCASE_BASE_PATH') or define('ADSHOWCASE_BASE_PATH', ArrayHelper::getValue($_ENV, 'ADSHOWCASE_BASE_PATH', __DIR__));
    defined('YII_ENV') or define('YII_ENV', ArrayHelper::getValue($_ENV, 'ADSHOWCASE_ENV'));
    defined('YII_DEBUG') or define('YII_DEBUG', YII_ENV == 'dev');

    require ADSHOWCASE_BASE_PATH . '/vendor/yiisoft/yii2/Yii.php';
    require ADSHOWCASE_BASE_PATH . '/config/bootstrap.php';

    $configApp = ArrayHelper::merge(
            require ADSHOWCASE_BASE_PATH . '/config/console.php',
            require ADSHOWCASE_BASE_PATH . '/config/main-' . YII_ENV . '.php'
    );

    $application = new Application($configApp);
    $exitCode = $application->run();
    exit($exitCode);
} catch (Throwable $exception) {
    dd($exception);
}